Fixed the root cause of the error with commit-all

diff --git a/git-commit-all b/git-commit-all
--- a/git-commit-all
+++ b/git-commit-all
@@ -1,7 +1,10 @@
 #!/bin/bash
 
 commit_msg=$1
-test -z $commit_msg && echo "Commit message cannot be empty." && exit 1
+if [[ -z $commit_msg ]]; then
+    echo "Commit message cannot be empty."
+    exit 1
+fi
 
 git add .
 git commit -m "$commit_msg"
